name: Bug Report
description: File a report to help us improve
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improving this configuration!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our sharable config are you running?
    validations:
      required: true
  - type: dropdown
    id: configs
    attributes:
      label: Please specify which subconfigurations be affected
      multiple: true
      options:
        - base
        - react
        - react-native
        - typescript
        - styled-components
  - type: input
    id: rules
    attributes:
      label: Rules
      description: What might be affected?
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Please copy and paste any relevant context information (e.g. log output). Do not attach ZIP files or screenshots of your code. Instead, please publish your code to a public GitHub repository or [stackblitz](https://stackblitz.com/) and post a link to it.
      placeholder: Add any other context about the problem here.
