name: Release on NPM
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ !(contains(github.event.head_commit.message, 'chore(release)')) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            token: ${{ secrets.ADMIN_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Release, push and publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.name 'GitHub Action Release [bot]'
          git config --global user.email 'actions@github.com'
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm run release && git push --follow-tags origin main && npm publish
